require conf/distro/poky.conf

INIT_MANAGER = "systemd"
DISTRO_FEATURES:append = " usrmerge systemd wifi grep cpufrequtils wpa-supplicant"
DISTRO_FEATURES:remove = " sysvinit"
VIRTUAL-RUNTIME_syslog = ""
VIRTUAL-RUNTIME_base-utils-syslog = ""
DISTRO_FEATURES:remove = "wayland"
DISTRO_FEATURES:append = "systemd"
DISTRO_FEATURES:append = "ssh-server-openssh"
LICENSE_FLAGS_ACCEPTED = "synaptics-killswitch"
ENABLE_I2C = "1"
KERNEL_MODULE_AUTOLOAD:rpi += "i2c-dev i2c-bcm2708"
DISTRO_FEATURES:append = " systemd"

IMAGE_INSTALL:append = " systemd-conf"
RUSTVERSION = "1.87%"
